#!/usr/bin/env bash
#
# Run the integration tests with the appropriate environment.
# Primarily for use in integration tests
#
# Shon Feder, 2020

# The directory of this file
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Ensure the environment is set
# shellcheck source=./.envrc
source "$DIR"/.envrc

# Ensure the mdx executable is on the path
eval "$(opam env)"

# Execute the wrapper script
"$DIR"/mdx-test.py
