#!/usr/bin/env bash
#
# Run the integration tests
#
# Igor Konnov, 2018

DIR=`dirname $0`
DIR=`cd "$DIR/.."; pwd`
echo "# Tool home: $DIR"
TEST_DIR="$DIR/test/tla"
nok=0
nfail=0
LOGFILE="$TEST_DIR/log.out"
echo "" >"$LOGFILE"

function tm() {
    date '+%H:%M:%S'
}

function check() {
    TEST=$1
    OUTF="$TEST.out"
    ERRF="$TEST.err"
    shift
    "$DIR"/bin/apalache-mc check $@ 2>"$ERRF" | tee "$OUTF"

    if grep -q "The outcome is: NoError" "$OUTF"; then
        RES=1
    elif grep -q "The outcome is: Error" "$OUTF"; then
        RES=0
    elif grep -q "REPORT A BUG" "$OUTF"; then
        RES=500
    else
        RES=10 # unknown bug
    fi
}

function expect_ok() {
    if [ "$RES" = "1" ]; then
        printf '%s TEST %-58s [OK]\n' `tm` "$TEST" >>"$LOGFILE"
        nok=$((nok+1))
    else
        printf '%s TEST %-58s [FAIL]\n' `tm` "$TEST" >>"$LOGFILE"
        nfail=$((nfail+1))
    fi
}

function expect_err() {
    if [ "$RES" = "0" ]; then
        printf '%s TEST %-58s [OK]\n' `tm` "$TEST" >>"$LOGFILE"
        nok=$((nok+1))
    else
        printf '%s TEST %-58s [FAIL]\n' `tm` "$TEST" >>"$LOGFILE"
        nfail=$((nfail+1))
    fi
}


cd "$DIR"
if [ "$NO_MVN" != "" ]; then
    echo "# Skipped mvn package, as NO_MVN=$NO_MVN"
else
    echo "# Building the package with Maven"
    mvn package
fi

echo "# Running the tests"
cd "$DIR/test/tla"
check "001-HourClock" --length=10 --init=HCini --next=HCnxt \
    --inv=TypeOK HourClock.tla \
    && expect_ok
check "002-Bug20190118" --length=1 --init=Init --next=Next \
    --inv=Inv Bug20190118.tla \
    && expect_ok
check "003-mis" --length=5 --inv=IsIndependent mis.tla \
    && expect_ok
check "004-mis_bug" --length=5 --inv=IsIndependent mis_bug.tla \
    && expect_err
# TODO: TypeOK of ast.tla does not work
check "005-ast" --length=5 ast.tla \
    && expect_ok
check "006-pr" --length=2 pr.tla \
    && expect_ok
check "007-EWD840" --length=5 --inv=Inv EWD840.tla \
    && expect_ok
check "008-Paxos" --length=5 --inv=Inv Paxos.tla \
    && expect_ok
check "009-Bug20190807" --length=1 Bug20190118.tla \
    && expect_ok
check "010-Bug20190921" --length=5 --cinit=CInit Bug20190921.tla \
    && expect_ok
check "011-Counter" --length=10 --inv=Inv Counter.tla \
    && expect_err
check "012-y2k" --length=20 --inv=Safety --cinit=ConstInit y2k_cinit.tla \
    && expect_err
check "013-y2k" --length=20 --inv=Safety y2k_instance.tla \
    && expect_ok
check "014-y2k" --length=30 --inv=Safety y2k_instance.tla \
    && expect_err
check "015-y2k" --length=20 --inv=Safety y2k_override.tla \
    && expect_ok
check "016-y2k" --length=30 --inv=Safety y2k_override.tla \
    && expect_err
check "017-NatCounter" --length=10 --inv=Inv NatCounter.tla \
    && expect_err

cat "$LOGFILE"

echo "OK: $nok FAILED: $nfail"

if [ "$nfail" -gt 0 ]; then
    echo "Some tests failed. Check ${TEST_DIR}/<test>.log."
    exit 1
fi

