
package at.forsyte.apalache.tla.lir

import scala.collection.immutable.{HashMap, Map, Set}
import java.io._

import com.microsoft.z3._
import at.forsyte.apalache.tla.lir.actions.TlaActionOper
import at.forsyte.apalache.tla.lir.oper.{TlaBoolOper, TlaSetOper}
import at.forsyte.apalache.tla.lir.plugins.UniqueDB

package object assignments{

  protected abstract class BoolFormula
  protected case class False() extends BoolFormula
  protected case class And( args : BoolFormula* ) extends BoolFormula
  protected case class Or( args : BoolFormula* ) extends BoolFormula
  protected case class Neg( arg : BoolFormula ) extends BoolFormula
  protected case class Implies( LHS : BoolFormula, RHS : BoolFormula ) extends BoolFormula
  protected case class Variable( id: Int ) extends BoolFormula
  protected case class LtFns( i: Int, j: Int )  extends BoolFormula // ( R( i ) < R( j ) )
  protected case class NeFns( i: Int, j: Int )  extends BoolFormula // ( R( i ) != R( j ) )

  protected var m_varSym = "A"
  protected var m_fnSym = "R"

//  def varSym : String = m_varSym
//  def varSym_=( p_sym : String ) : Unit = {
//    m_varSym = p_sym
//  }
//
//  def fnSym : String = m_fnSym
//  def fnSym_=( p_sym : String ) : Unit = {
//    m_fnSym = p_sym
//  }

  protected def toSmt2( phi : BoolFormula, varSym: String = "A", fnSym : String = "R" ) : String = {
    phi match{
      case False() => "false" //"( false )"
      case And( args@_* ) => "( and %s )".format( args.map( toSmt2( _, varSym, fnSym ) ).mkString(" ") )
      case Or( args@_* ) => "( or %s )".format( args.map( toSmt2( _, varSym, fnSym ) ).mkString(" ") )
      case Neg( arg : BoolFormula ) => "( not %s )".format( toSmt2( arg ) )
      case Implies( lhs, rhs ) => "( => %s %s )".format( toSmt2( lhs ), toSmt2( rhs ) )
      case Variable( id: Int ) => varSym + "_" + id //"( %s_%s )".format( varSym, id )
      case LtFns( i: Int, j: Int ) => "( < ( %s %s ) ( %s %s ) )".format( fnSym, i, fnSym, j )
      case NeFns( i: Int, j: Int ) => "( not ( = ( %s %s ) ( %s %s ) ) )".format( fnSym, i, fnSym, j )
    }
  }

  // Assusme input generated by a delta_v function
  protected def simplify( phi: BoolFormula ) : BoolFormula = {
    phi match {
      case And( args@_*) => {
        val newargs = args.map(simplify)
        if ( newargs.contains( False() ) )
          False()
        else
          And( newargs:_* )
      }
      case Or( args@_*) => {
        val newargs = args.map(simplify).filterNot( _ == False() )
        newargs.size match {
          case 0 => False()
          case 1 => newargs.head
          case _ =>Or( newargs:_* )
        }
      }
      case _ => phi
    }
  }

  protected def delta( v: NameEx )( phi: OperEx ) : BoolFormula = {
    // assume well-formedndess, i.e. only and/or/in
    phi.oper match {
      case TlaBoolOper.and => Or( phi.args.map( arg => delta(v)( arg.asInstanceOf[OperEx] ) ):_* )
      case TlaBoolOper.or => And( phi.args.map( arg => delta(v)( arg.asInstanceOf[OperEx] ) ):_* )
      case TlaSetOper.in => {
        phi.args.head match {
          case OperEx( TlaActionOper.prime, NameEx( name ) ) => {
            if( v == NameEx( name ) )
              Variable( phi.ID.id )
            else
              False()
          }
          case _ => False()
        }
      }
      case _ => False()
    }
  }

  // assume i in rage for sanity
  protected def lvar( i : Int ) : NameEx = UniqueDB.apply( UID( i ) ).
    head.asInstanceOf[OperEx].args.
    head.asInstanceOf[OperEx].args.
    head.asInstanceOf[NameEx]

  protected def findPrimes( ex : TlaEx ) : Set[NameEx] = {
    ex match {
      case OperEx( TlaActionOper.prime, NameEx(n) ) => Set(NameEx(n))
      case OperEx( _, args@_* ) => args.map( findPrimes ).fold( Set[NameEx]() ){ (a,b) => a ++ b }
      case _ => Set[NameEx]()
    }
  }
  protected def rvars( i : Int ) : Set[NameEx] = {
    findPrimes(
      UniqueDB(UID(i)).head.asInstanceOf[OperEx].args.tail.head // 2nd arg is the RHS
    )
  }

  protected def sqsubset( i: Int, j: Int ): Boolean = rvars( j ) contains lvar( i )

  // assume no equalities, all of the form a \in B
  protected def massProcess( p_phi : TlaEx, p_vars: Set[NameEx] )
    : ( Set[Int], Set[(Int,Int)], Map[NameEx,BoolFormula] ) = {
    val ret = innerMassProcess(p_phi,p_vars)
    (ret._1, ret._2, ret._4.map( pa => (pa._1, simplify(pa._2) ) ) )
  }
  protected def innerMassProcess( p_phi : TlaEx, p_vars: Set[NameEx] )
                : ( Set[Int], Set[(Int,Int)], Set[(Int,Int)], Map[NameEx,BoolFormula] ) = {

    val defaultMap = ( for {v <- p_vars} yield (v, False()) ).toMap
    val defaultArgs = ( Set[Int](), Set[(Int,Int)](), Set[(Int,Int)](), defaultMap )

    p_phi match {
      case OperEx(oper, args@_*) =>
        oper match{
          case TlaBoolOper.and | TlaBoolOper.or =>
            // OKCheck : simply recurse, take forall
            // label : simply recurse, do foreach
            // D : All unprocessed children on all branches are dependent/indep.

            val processedArgs = args.map( innerMassProcess( _, p_vars) )

            // CONTINUE HERE
            val newMapArgs =
              ( for { v <- p_vars } yield
                ( v,
                  processedArgs.map(
                    tpl => tpl._4
                  ).map(
                    _.get(v)
                  ).filterNot( _.isEmpty ).map(
                    _.head
                  )
                )
              ).toMap

            val ( seen, depSet, indepSet, _ ) = processedArgs.fold(
              defaultArgs
            ){
              ( a,b ) => ( a._1 ++ b._1,
                           a._2 ++ b._2,
                           a._3 ++ b._3,
                           defaultArgs._4 // irrelevant
              )
            }

            val newMap : Map[NameEx,BoolFormula] =
              (
                for { v <- p_vars }
                  yield ( v,
                          if (oper == TlaBoolOper.and)
                            Or(newMapArgs(v):_*)
                          else
                            And(newMapArgs(v):_*)
                        )
              ).toMap

            val S : Set[(Int,Int)] = for { x <- seen; y <- seen } yield (x,y)

            // all unprocessed pairs are dep., guaranteed n1 > n0
            oper match {
              case TlaBoolOper.and => ( seen, S -- indepSet, indepSet, newMap )
              case TlaBoolOper.or  => ( seen, depSet, S -- depSet, newMap )
            }
          case TlaSetOper.in =>
            args.head match {
              case OperEx( TlaActionOper.prime, nameEx ) =>
                val n : Int = p_phi.ID.id
                val newmap = ( for { v <- p_vars } yield (v, if( nameEx == v ) Variable( n ) else False() ) ).toMap
                ( Set[Int](n), Set[(Int,Int)]( (n,n) ), Set[(Int,Int)](), newmap )
              case _ => defaultArgs // not an assignment for sure
            }
          case _ => defaultArgs
        }
        // no info, we KNOW toplevel call is on an OperEx
      case _ => defaultArgs
    }
  }


  def makeSpec( p_vars: Set[NameEx],
                p_phi : OperEx,
                p_mkFile : Option[String] = None
              ) : String = {

    val ( seen, deps, deltas ) = massProcess(p_phi, p_vars)

    val simpleDeltas = ( for {v <- p_vars} yield ( v, simplify( deltas(v) ) ) ).toMap

    val D_sqss = deps.filter( pa =>  sqsubset( pa._1, pa._2 ) )
    val D_exOne = deps.filter( pa => pa._1 < pa._2 && lvar( pa._1 ) == lvar( pa._2) )

    val aargs = simpleDeltas.values
    val aargsSMT = aargs.map( toSmt2(_) )
    val rargs =
      for { (i,j) <- D_sqss }
      yield
        Implies(
          And( Variable( i ),
               Variable( j )
          ),
          LtFns( i, j )
        )
    val rargsSMT = rargs.map( toSmt2(_) )
    val injargs = for { i <- seen; j <- seen if i < j} yield NeFns(i, j)
    val injargsSMT = injargs.map( toSmt2(_) )
    val exOneargs =
      for { (i,j) <- D_exOne }
        yield Neg( And( Variable( i ), Variable( j ) ) )
    val exOneargsSMT = exOneargs.map( toSmt2(_) )

    val typedecls = seen.map( "( declare-fun %s_%s () Bool )".format( m_varSym, _ ) ).mkString("\n")
    val fndecls = "\n( declare-fun %s ( Int ) Int )\n".format( m_fnSym)
    val constraints = ( aargsSMT ++ rargsSMT ++ injargsSMT ++ exOneargsSMT ).toSeq.map(
      str => "( assert %s )".format( str )
    ).mkString("\n")

    val ret = typedecls + fndecls + constraints

    if( p_mkFile.nonEmpty ) {

      val logic = "( set-logic QF_UFLIA )\n"
      val end = "\n( check-sat )\n( get-model )\n( exit )"

      def save( fname: String ) : Unit = {
        val pw = new PrintWriter(new File( fname ) )
        pw.write(logic + ret + end)
        pw.close()
      }

      p_mkFile.foreach( save )

    }
    ret
  }

  class FunWrapper( f: FuncInterp ) {
    protected val m_default : Int = f.getElse.asInstanceOf[IntNum].getInt

    protected val m_map : Map[String, Int] =
      ( for { e: FuncInterp.Entry <- f.getEntries }
          yield (
                  "%s_%s".format(m_varSym,e.getArgs.head ),
                  e.getValue.asInstanceOf[IntNum].getInt
                )
      ).toMap

    def apply( arg: String ): Int = m_map.getOrElse( arg, m_default )

    override def toString: String = m_map.toString

//
//    val temp = m_args.map( x=> x. )

  }

  def getOrder( p_spec : String ) : Option[Seq[(UID,Boolean)]] = {
    val ctx = new Context()
    val s = ctx.mkSolver()
    s.add( ctx.parseSMTLIB2String( p_spec, null, null, null, null ) )

    val status = s.check.toString

    if( status != "SATISFIABLE" )
      return None

    val m = s.getModel

    val fnDecl = m.getFuncDecls

    if( fnDecl.size != 1 )
      return None

    val fnInterp = m.getFuncInterp( fnDecl(0) )

    val wrap = new FunWrapper( fnInterp )

    val varInterps = m.getConstDecls.map( x=> ( m.getConstInterp( x ), x.getName.toString ) )

    val ranks = varInterps.sortBy(  x => wrap( x._2 ) )
//    ranks.foreach( println )

    val ret = ranks.map(
        x => (
          UID( x._2.substring(2).toInt ),
          x._1.getBoolValue.toInt == 1 // WHY T.F. is there no .toBool????
        )
      )

    return Some( ret )
  }

  def getOrder( p_vars: Set[NameEx],
                p_phi : OperEx,
                p_mkFile : Option[String]
              ) : Option[Seq[(UID,Boolean)]] = {
    val spec = makeSpec(p_vars,p_phi,p_mkFile)
    getOrder( spec )
  }

}


