[book]
title = "Apalache Documentation"
authors = ["Igor Konnov", "Jure Kukovec", "Andrey Kuprianov", "Shon Feder"]
src = "src"
language = "en"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/informalsystems/apalache"

[build]
build-dir = "../target/docs"
# Don't create empty files when a chapter doesn't exist
create-missing = false
# Don't rename README.md to index.md
use-default-preprocessors = false

# Do allow for file inclusion via {{ #include }}
[preprocessor.links]
